### ISSUE TITLE
The dataset provided does not include graph_dict.pkl. The code will be unable to run as the result.

### ISSUE THREAD

**Issue by Kizzen983** [AONE-NLP/DiffuTKG#2]
In the code provided by the author, there is a section of code at line 242 of main_21.py
`    with open(os.path.join('/data/lxc/datasets/DiffuTKG/{}/'.format(args.dataset) , 'graph_dict.pkl'), 'rb') as fp:
        graph_dict = pickle.load(fp)`
However, **there is no graph_dict.pkl in any of the provided datasets**. The code will be unable to run as the result.

**Comment by Kizzen983** [comment]
The problem has been resolved

**Comment by Inrstning** [comment]
We have the same two problems. How did you solve them?
